set $mod Mod4

set $left h
set $down j
set $up k
set $right l

set $screen_locker swaylock

set $launch exec uwsm app --

set $term $launch alacritty

set $menu ~/.config/scripts/sway/launch.sh

set $file_manager $launch nautilus
