set $mod Mod4

set $left h
set $down j
set $up k
set $right l

set $screen_locker swaylock

set $launch exec uwsm app --

set $term $launch alacritty

set $menu $launch "$(wofi --show drun --define=drun-print_desktop_file=true | sed -E "s/(\.desktop) /\1:/")"

set $file_manager $launch nautilus
