[general]
import = [ "colors.matugen.toml" ]

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "R", mods = "Control|Shift", action = "ResetFontSize" }
]

[window]
padding = { x = 16, y = 16 }

[font]
size = 11
