[colors.primary]
background = '#101418'
foreground = '#e0e2e8'
 
[colors.cursor]
text = '#42474e'
cursor = '#e0e2e8' 
 
[colors.vi_mode_cursor]
text = '#101418'
cursor = '#9dcbfc' 
 
[colors.search.matches]
foreground = '#42474e' 
background = '#d4bee6' 
 
[colors.search.focused_match]
foreground = '#42474e' 
background = '#9dcbfc' 
 
[colors.footer_bar]
foreground = '#42474e' 
background = '#e0e2e8' 
 
[colors.hints.start]
foreground = '#42474e' 
background = '#bac8da' 
 
[colors.hints.end]
foreground = '#42474e' 
background = '#bac8da' 
 
[colors.selection]
text = '#003355'
background = '#9dcbfc'
 
 
[colors.normal]
black = '#101418'
red = '#ffb2be' 
green = '#99d4a2' 
yellow = '#cacb77' 
blue = '#a8c8ff' 
magenta = '#d9bafa' 
cyan = '#83d5c7' 
white = '#bfce7f' 
 
 
[colors.bright]
black = '#1d2024'
red = '#561d2a' 
green = '#003918' 
yellow = '#313300' 
blue = '#07305f' 
magenta = '#3d2459' 
cyan = '#003731' 
white = '#2b3400' 

[colors.dim]
black = "#131415"
red = "#864343"
green = "#777c44"
yellow = "#9e824c"
blue = "#556a7d"
magenta = "#75617b"
cyan = "#5b7d78"
white = "#828482"
