[colors.primary]
background = '{{colors.surface.default.hex}}'
foreground = '{{colors.on_surface.default.hex}}'
 
[colors.cursor]
text = '{{colors.surface_variant.default.hex}}'
cursor = '{{colors.on_surface.default.hex}}' 
 
[colors.vi_mode_cursor]
text = '{{colors.background.default.hex}}'
cursor = '{{colors.primary.default.hex}}' 
 
[colors.search.matches]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.tertiary.default.hex}}' 
 
[colors.search.focused_match]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.primary.default.hex}}' 
 
[colors.footer_bar]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.inverse_surface.default.hex}}' 
 
[colors.hints.start]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.secondary.default.hex}}' 
 
[colors.hints.end]
foreground = '{{colors.surface_variant.default.hex}}' 
background = '{{colors.secondary.default.hex}}' 
 
[colors.selection]
text = '{{colors.on_primary.default.hex}}'
background = '{{colors.primary.default.hex}}'
 
 
[colors.normal]
black = '{{colors.background.default.hex}}'
red = '{{colors.red.default.hex}}' 
green = '{{colors.green.default.hex}}' 
yellow = '{{colors.yellow.default.hex}}' 
blue = '{{colors.blue.default.hex}}' 
magenta = '{{colors.magenta.default.hex}}' 
cyan = '{{colors.cyan.default.hex}}' 
white = '{{colors.white.default.hex}}' 
 
 
[colors.bright]
black = '{{colors.surface_container.default.hex}}'
red = '{{colors.on_red.default.hex}}' 
green = '{{colors.on_green.default.hex}}' 
yellow = '{{colors.on_yellow.default.hex}}' 
blue = '{{colors.on_blue.default.hex}}' 
magenta = '{{colors.on_magenta.default.hex}}' 
cyan = '{{colors.on_cyan.default.hex}}' 
white = '{{colors.on_white.default.hex}}' 

[colors.dim]
black = "#131415"
red = "#864343"
green = "#777c44"
yellow = "#9e824c"
blue = "#556a7d"
magenta = "#75617b"
cyan = "#5b7d78"
white = "#828482"
